version: "3"

services:
  proxy:
    build:
      context: nginx
    container_name: proxy
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - node-network
    depends_on:
      - app

  app:
    build:
      context: node
    container_name: app
    restart: always
    entrypoint: node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
